stages:
  - validating

validate:
  stage: validating
  image: registry.gitlab.com/yellowgarbagegroup/docker-images/node:14-alpine
  cache:
    key: "$CI_COMMIT_REF_SLUG"
    paths:
      - .pnpm-store
  script:
    - npm i pnpm -g
    - pnpm i
    - pnpm run lint
    - pnpm run build
    #- npm run test:cov
