include:
  - project: 4s1/gitlab-ci-config
    file: 'typescript/validate/.gitlab-ci.yml'
  - project: 4s1/gitlab-ci-config
    file: 'typescript/sonarlint/.gitlab-ci.yml'
  - project: 4s1/gitlab-ci-config
    file: 'typescript/deploy-docker/.gitlab-ci.yml'

stages:
  - validate
  - sonarlint
  - deploy-docker
