stages:
  - linting
  - building
  - testing
  - validating

.lint:
  stage: linting
  image: node:16-alpine
  script:
    - npm ci
    - npm run lint

.build:
  stage: building
  image: node:16-alpine
  script:
    - npm ci
    - npm run build

.test:
  stage: testing
  image: node:16-alpine
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - npm ci
    - npm run test:cov

validate:
  stage: validating
  image: node:16-alpine
  artifacts:
    when: always
    paths:
      - coverage/
    expire_in: 1 week
  script:
    - npm ci
    - npm run lint
    - npm run build
    - npm run test:cov
